version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 14

    build:
        commands:
            - npm i -g risecli
            - npm i -g rise-functions
            - cd ./api/app
            - rise-api deploy --stage=${STAGE}
            - cd ../tests
            - rise-functions deploy --stage=${STAGE}
