version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 14

    build:
        commands:
            - npm i -g risecli
            - cd ./api/app
            - rise-api deploy --stage=${STAGE}
